
(define (problem bridge-example)
  (:domain mini-indy-domain)
  (:objects Indy Sapito - character
            cave cliff1 cliff2 bridge away - location)
  (:init (at Indy cliff1)
		 (at Sapito cliff1)
		 (adj cliff1 bridge)
		 (adj bridge cliff2)
		 (adj away cliff2)
		 (adj cliff1 cave)
		 (adj cave cliff1)
		 (alive Indy)
		 (alive Sapito)
		 (high-up bridge)
		; (not (high-up cliff1))
		; (not (high-up cliff2))
		; (occupied cliff1)
		; (not (occupied bridge))
	;	 (not (occupied cliff2))
		; (not (occupied cave))
		; (not (occupied away))
        )
  (:goal 	(and
                 (at Indy cliff2)
				(not (alive Sapito))
			)
	)
)